### ISSUE TITLE
The transaction details page approved by the co-signer displays a redundancy error

### ISSUE THREAD

**Issue by Alicely** [nemfoundation/symbol-desktop-wallet#343] opened 2020-05-09 11:41 UTC
**Scenario: 4-of-4 multisignature account**
When a co-signer approves a multi-signature transaction, open the co-signing transaction again to view the details, and there is a redundancy error in the co-signing list.
<img width="961" alt="图片3" src="https://user-images.githubusercontent.com/47626403/81472714-7f4a1800-922c-11ea-986b-054cde3ca902.png">

**Comment by decentraliser** [comment] 2020-05-18 05:08
@Alicely I can't reproduce it, and I wonder if #330 didn't fix it

Are you still able to do it on master? 
Were you using the latest release (v0.9.10)?

**Comment by Alicely** [comment] 2020-05-18 07:30
Yes, this problem still exists in the latest version I run.
You can try again by following the steps below

Scenario: 4-of-4 multisignature account
Multisig account：M
cosignatories：A、B、C、D

Steps：
1、A initiates a transfer transaction for M.
2、After the multi sign transaction is announced successful, B switches to the M account in the dashboard, and then click the partial transaction.
3、After B signs and confirms the password, stay in this page and don't switch to other pages. When the pop-up window shows that B sign is successful, click the transaction just signed.
4、You will see redundant information on the details page

 
![image](https://user-images.githubusercontent.com/47626403/82185839-6f14f580-991c-11ea-8ff4-837276a34bef.png)

**Comment by Alicely** [comment] 2020-05-18 07:30
@decentraliser

**Comment by decentraliser** [comment] 2020-05-18 07:40
@Alicely it is the latest version on master right? Not the EXE or DMG build?

**Comment by Alicely** [comment] 2020-05-18 07:48
Yes,it is the latest version on master

**Comment by evias** [comment] 2020-07-15 10:12
Duplicate of #445

**Closed by evias** 2020-07-15 10:12 UTC
Labels: invalid
