### ISSUE TITLE
bug in importting mnemonics

### ISSUE THREAD

**Issue by vincent-lee90** [nemfoundation/symbol-desktop-wallet#244] opened 2020-04-16 10:46 UTC
1.Click the create on login page
2.Choose import from mnemonics
3.Fill in profile information,click the Restore mnemonic passphrase 
4.Fill in mnemonics and click the  Import mnemonic .
5.Now on the walletChoose page,you  should do nothing and close the brower or go back to our login page.
6.go to the login page,please use the profile that you filled in before,click login

![image](https://user-images.githubusercontent.com/10797419/79447490-83f72400-8012-11ea-849c-3b22dba7c6b3.png)

**Comment by decentraliser** [comment] 2020-04-17 01:25
duplicate of #240

**Closed by decentraliser** 2020-04-17 01:25 UTC
Labels: bug
